# filename: sdl_test.yaml

esphome:
  name: sdl
  platform: native

logger:

api:
  on_client_connected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.show: lbl_hastatus
  on_client_disconnected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.hide: lbl_hastatus

display:
  - platform: sdl
    dimensions:
      width: 800
      height: 480
    show_test_card: false

# Minimal icon font for nav + status
font:
  - file: 'fonts/FontAwesome5-Solid+Brands+Regular.woff'
    id: fa_20
    size: 20
    bpp: 4
    glyphs: [
      "\uF053", # angle-left
      "\uF054", # angle-right
      "\uF015", # home
      "\uF1EB", # wifi
    ]

lvgl:
  theme:
    label:
      text_color: 0xFFFFFF
    button:
      bg_color: 0x2F8CD8
      bg_grad_color: 0x005782
      bg_grad_dir: VER
      bg_opa: COVER
      border_color: 0x0077b3
      border_width: 1
      text_color: 0xFFFFFF
      pressed:
        bg_color: 0x006699
        bg_grad_color: 0x00334d
    buttonmatrix:
      bg_opa: TRANSP
      border_width: 0
      text_color: 0xFFFFFF
      items:
        bg_color: 0x2F8CD8
        bg_grad_color: 0x005782
        bg_grad_dir: VER
        bg_opa: COVER
        border_color: 0x0077b3
        border_width: 1
        text_color: 0xFFFFFF

  style_definitions:
    - id: header_footer
      bg_color: 0x2F8CD8
      bg_grad_color: 0x005782
      bg_grad_dir: VER
      bg_opa: COVER
      border_opa: TRANSP
      radius: 0
      pad_all: 0
      pad_row: 0
      pad_column: 0
      border_color: 0x0077b3
      text_color: 0xFFFFFF
      width: 100%
      height: 30

  top_layer:
    widgets:
      - buttonmatrix:
          align: bottom_mid
          styles: header_footer
          pad_all: 0
          outline_width: 0
          id: nav_bar
          items:
            styles: header_footer
          rows:
            - buttons:
              - id: page_prev
                text: "\uF053"
                on_press:
                  then:
                    lvgl.page.previous:
              - id: page_home
                text: "\uF015"
                on_press:
                  then:
                    lvgl.page.show: home_page
              - id: page_next
                text: "\uF054"
                on_press:
                  then:
                    lvgl.page.next:

      - label:
          text: "\uF1EB"
          id: lbl_hastatus
          hidden: true
          align: top_right
          x: -6
          y: 6
          text_align: right
          text_font: fa_20
          text_color: 0xFFFFFF

  pages:
    - id: home_page
      widgets:
        - obj:
            width: 800
            height: 480
            bg_color: 0x464B55
            border_width: 0
            pad_all: 10
            widgets:
              - obj:
                  align: TOP_MID
                  styles: header_footer
                  widgets:
                    - label:
                        text: "ESPHome LVGL Test"
                        align: CENTER
                        text_align: CENTER
                        text_color: 0xFFFFFF

              - dropdown:
                  id: page_selector
                  align: TOP_MID
                  y: 60
                  width: 220
                  options:
                    - "Home"
                    - "Control"
                  selected_index: 0
                  on_value:
                    - if:
                        condition:
                          lambda: 'return (int)x == 0;'
                        then:
                          - lvgl.page.show: home_page
                    - if:
                        condition:
                          lambda: 'return (int)x == 1;'
                        then:
                          - lvgl.page.show: control_page

              - line:
                  id: flow_temp_line
                  align: CENTER
                  x: -50
                  y: 0
                  width: 400
                  height: 200
                  points:
                    - { x: 0, y: 100 }
                    - { x: 40, y: 95 }
                    - { x: 80, y: 92 }
                    - { x: 120, y: 98 }
                    - { x: 160, y: 90 }
                    - { x: 200, y: 94 }
                    - { x: 240, y: 91 }
                    - { x: 280, y: 93 }
                    - { x: 320, y: 89 }
                    - { x: 360, y: 95 }
                  line_color: 0x33A1FF
                  line_width: 2

              - line:
                  id: outdoor_temp_line
                  align: CENTER
                  x: 150
                  y: 0
                  width: 400
                  height: 200
                  points:
                    - { x: 0, y: 110 }
                    - { x: 40, y: 112 }
                    - { x: 80, y: 115 }
                    - { x: 120, y: 113 }
                    - { x: 160, y: 118 }
                    - { x: 200, y: 116 }
                    - { x: 240, y: 119 }
                    - { x: 280, y: 117 }
                    - { x: 320, y: 121 }
                    - { x: 360, y: 118 }
                  line_color: 0xFF9933
                  line_width: 2

    - id: control_page
      widgets:
        - obj:
            width: 800
            height: 480
            bg_color: 0x464B55
            border_width: 0
            pad_all: 10
            widgets:
              - obj:
                  align: TOP_MID
                  styles: header_footer
                  widgets:
                    - label:
                        text: "Control Page"
                        align: CENTER
                        text_align: CENTER
                        text_color: 0xFFFFFF

              - arc:
                  id: temp_dial
                  align: CENTER
                  x: -200
                  y: 0
                  width: 200
                  height: 200
                  min_value: 20
                  max_value: 65
                  value: 45
                  rotation: 135
                  start_angle: 135
                  end_angle: 45
                  arc_color: 0x33A1FF
                  arc_width: 15
                  adjustable: true
                  on_value:
                    - lambda: |-
                        float temp = x;
                        ESP_LOGD("DIAL", "Temperature set to: %.1f", temp);

              - label:
                  id: temp_dial_label
                  align: CENTER
                  x: -200
                  y: 0
                  text: "45°C"
                  text_font: montserrat_32
                  text_color: 0x33A1FF

              - obj:
                  id: temp_container
                  align: CENTER
                  x: 150
                  y: 0
                  width: 300
                  height: 300
                  bg_color: 0x535966
                  border_width: 0
                  pad_all: 15
                  widgets:
                    - label:
                        text: "Flow Temp"
                        align: TOP_LEFT
                        y: 10
                        text_font: montserrat_16
                        text_color: 0xFFFFFF
                    - label:
                        id: flow_temp_value
                        text: "--°C"
                        align: TOP_LEFT
                        y: 35
                        text_font: montserrat_24
                        text_color: 0x33A1FF
                    - label:
                        text: "Outdoor Temp"
                        align: TOP_LEFT
                        y: 90
                        text_font: montserrat_16
                        text_color: 0xFFFFFF
                    - label:
                        id: outdoor_temp_value
                        text: "--°C"
                        align: TOP_LEFT
                        y: 115
                        text_font: montserrat_24
                        text_color: 0xFF9933
