# filename: sdl_test.yaml

esphome:
  name: sdl
  platform: native

logger:

api:
  on_client_connected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.show: lbl_hastatus
  on_client_disconnected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.hide: lbl_hastatus

display:
  - platform: sdl
    dimensions:
      width: 800
      height: 480
    show_test_card: false

# Minimal icon font for nav + status
font:
  - file: 'fonts/FontAwesome5-Solid+Brands+Regular.woff'
    id: fa_20
    size: 20
    bpp: 4
    glyphs: [
      "\uF053", # angle-left
      "\uF054", # angle-right
      "\uF015", # home
      "\uF1EB", # wifi
    ]


                          - label:
                              id: power_text
                              text_font: montserrat_20
                              align: CENTER
                              y: 56
                              text: "--.- kW"
                              text_color: 0xFFD54F

                    - label:
                        text: "Compressor Frequency"
                        align: TOP_MID
                        y: 196
                        text_font: montserrat_16
                        text_color: 0xFFFFFF
                    - obj:
                        id: freq_gauge_box
                        align: TOP_MID
                        y: 218
                        width: 240
                        height: 160
                        bg_color: 0x2B2F36
                        border_width: 0
                        pad_all: 6
                        widgets:
                          - meter:
                              id: freq_meter
                              height: 100%
                              width: 100%
                              border_width: 0
                              bg_opa: TRANSP
                              align: CENTER
                              scales:
                                - range_from: 0
                                  range_to: 90
                                  angle_range: 180
                                  rotation: 180
                                  ticks:
                                    count: 0
                                  indicators:
                                    - arc:
                                        color: 0x2468B3
                                        r_mod: 12
                                        width: 22
                                        start_value: 0
                                        end_value: 45
                                    - arc:
                                        color: 0xE0621A
                                        r_mod: 12
                                        width: 22
                                        start_value: 45
                                        end_value: 90
                                - range_from: 0
                                  range_to: 90
                                  angle_range: 180
                                  rotation: 180
                                  ticks:
                                    count: 0
                                  indicators:
                                    - line:
                                        id: freq_needle
                                        width: 5
                                        color: 0xFFC107
                                        r_mod: 8
                                        value: 0
                        
                          - label:
                              id: freq_text
                              text_font: montserrat_20
                              align: CENTER
                              y: 56
                              text: "-- Hz"
                              text_color: 0xFFD54F

              - obj:
                  id: temp_container
                  align: RIGHT_MID
                  x: 0
                  y: 0
                  width: 200
                  height: 300
                  bg_color: 0x535966
                  border_width: 0
                  pad_all: 15
                  widgets:
                    - label:
                        text: "Flow Temp"
                        align: TOP_LEFT
                        y: 10
                        text_font: montserrat_16
                        text_color: 0xFFFFFF
                    - label:
                        id: flow_temp_value
                        text: "--°C"
                        align: TOP_LEFT
                        y: 35
                        text_font: montserrat_24
                        text_color: 0x33A1FF
                    - label:
                        text: "Outdoor Temp"
                        align: TOP_LEFT
                        y: 90
                        text_font: montserrat_16
                        text_color: 0xFFFFFF
                    - label:
                        id: outdoor_temp_value
                        text: "--°C"
                        align: TOP_LEFT
                        y: 115
                        text_font: montserrat_24
                        text_color: 0xFF9933
                    - label:
                        text: "Max Flow Temp"
                        align: TOP_LEFT
                        y: 170
                        text_font: montserrat_16
                        text_color: 0xFFFFFF
                    - label:
                        id: set_max_flow_temp_value
                        text: "--°C"
                        align: TOP_LEFT
                        y: 195
                        text_font: montserrat_24
                        text_color: 0x33A1FF

    - id: control_page
      widgets:
        - obj:
            width: 800
            height: 480
            bg_color: 0x464B55
            border_width: 0
            pad_all: 10
            widgets:
              - obj:
                  align: TOP_MID
                  styles: header_footer
                  widgets:
                    - label:
                        text: "Control Page"
                        align: CENTER
                        text_align: CENTER
                        text_color: 0xFFFFFF

              - obj:
                  id: max_dial_container
                  align: LEFT_MID
                  x: 40
                  y: 0
                  width: 300
                  height: 300
                  bg_color: 0x2B2F36
                  border_width: 0
                  pad_all: 15
                  widgets:
                    - label:
                        text: "Set Max Flow Temp"
                        align: TOP_MID
                        y: 10
                        text_font: montserrat_16
                        text_color: 0xFFFFFF
                    - arc:
                        id: max_temp_dial
                        align: CENTER
                        y: 12
                        width: 200
                        height: 200
                        min_value: 20
                        max_value: 65
                        value: 45
                        rotation: 0
                        start_angle: 135
                        end_angle: 45
                        arc_color: 0x2468B3
                        arc_width: 14
                        adjustable: true
                        on_value:
                          - lvgl.label.update:
                              id: max_temp_dial_label
                              text:
                                format: "%.0f°C"
                                args: [ 'x' ]
                        on_release:
                          - homeassistant.action:
                              action: number.set_value
                              data:
                                entity_id: number.set_max_flow_temp
                                value: !lambda return x;
                    # - obj:
                    #     height: 14
                    #     width: 14
                    #     radius: 7
                    #     align: CENTER
                    #     border_width: 0
                    #     pad_all: 0
                    #     bg_color: 0xFFC107
                    - label:
                        id: max_temp_dial_label
                        align: BOTTOM_MID
                        y: 2
                        text: "45°C"
                        text_font: montserrat_32
                        text_color: 0xFFD54F

              - obj:
                  id: min_dial_container
                  align: RIGHT_MID
                  x: -40
                  y: 0
                  width: 300
                  height: 300
                  bg_color: 0x2B2F36
                  border_width: 0
                  pad_all: 15
                  widgets:
                    - label:
                        text: "Set Min Flow Temp"
                        align: TOP_MID
                        y: 10
                        text_font: montserrat_16
                        text_color: 0xFFFFFF
                    - arc:
                        id: min_temp_dial
                        align: CENTER
                        y: 12
                        width: 200
                        height: 200
                        min_value: 20
                        max_value: 65
                        value: 45
                        rotation: 0
                        start_angle: 135
                        end_angle: 45
                        arc_color: 0x2468B3
                        arc_width: 14
                        adjustable: true
                        on_value:
                          - lvgl.label.update:
                              id: min_temp_dial_label
                              text:
                                format: "%.0f°C"
                                args: [ 'x' ]
                        on_release:
                          - homeassistant.action:
                              action: number.set_value
                              data:
                                entity_id: number.set_min_flow_temp
                                value: !lambda return x;
                  
                    - label:
                        id: min_temp_dial_label
                        align: BOTTOM_MID
                        y: 2
                        text: "45°C"
                        text_font: montserrat_32
                        text_color: 0xFFD54F

              
              - switch:
                  id: lv_sw_weather_comp
                  align: BOTTOM_MID
                  y: -60
                  width: 96
                  height: 44
                  bg_color: 0x1F5AA6
                  indicator:
                    bg_color: 0x1F5AA6
                  knob:
                    bg_color: 0xFFFFFF
                  checked:
                    bg_color: 0x2E7D32
                  on_click:
                    - if:
                        condition:
                          lambda: 'return id(weather_comp).state;'
                        then:
                          - switch.turn_off: weather_comp
                        else:
                          - switch.turn_on: weather_comp
              - label:
                  text: "Weather Compensation"
                  align: BOTTOM_MID
                  y: -20
                  text_font: montserrat_16
                  text_color: 0xFFFFFF
